// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9QyuARERCtRQJHCr64Qj1UZgzvbycs4k',
    appId: '1:576654875808:web:80d419856226c3e227bdc5',
    messagingSenderId: '576654875808',
    projectId: 'bulkfitness-70d48',
    authDomain: 'bulkfitness-70d48.firebaseapp.com',
    storageBucket: 'bulkfitness-70d48.firebasestorage.app',
    measurementId: 'G-3F7SFZ0HSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBDoBkhVhNJ3Edz-WkWEobS_V_eWDs94',
    appId: '1:576654875808:android:0eb7468d607c336827bdc5',
    messagingSenderId: '576654875808',
    projectId: 'bulkfitness-70d48',
    storageBucket: 'bulkfitness-70d48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKxU_pbPRUwligpC8NdCM5VjgxmNCEFU',
    appId: '1:576654875808:ios:1d442ac8f25885f027bdc5',
    messagingSenderId: '576654875808',
    projectId: 'bulkfitness-70d48',
    storageBucket: 'bulkfitness-70d48.firebasestorage.app',
    iosBundleId: 'com.example.bulkfitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKxU_pbPRUwligpC8NdCM5VjgxmNCEFU',
    appId: '1:576654875808:ios:1d442ac8f25885f027bdc5',
    messagingSenderId: '576654875808',
    projectId: 'bulkfitness-70d48',
    storageBucket: 'bulkfitness-70d48.firebasestorage.app',
    iosBundleId: 'com.example.bulkfitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9QyuARERCtRQJHCr64Qj1UZgzvbycs4k',
    appId: '1:576654875808:web:17ca8163ad54c9ae27bdc5',
    messagingSenderId: '576654875808',
    projectId: 'bulkfitness-70d48',
    authDomain: 'bulkfitness-70d48.firebaseapp.com',
    storageBucket: 'bulkfitness-70d48.firebasestorage.app',
    measurementId: 'G-W8XC4NNJSE',
  );
}
